- tests/test_config.py
> make test_toml_config_table_dumps use patched tmp_path

- ecoscope_workflows/tasks/results/__init__.py
- ecoscope_workflows/tasks/results/_ecoplot.py
- tests/tasks/test_ecoplot.py
> Task for drawing an EcoPlot

- ecoscope_workflows/connections.py
- tests/tasks/test_io_earthranger.py
- tests/test_connections.py
- tests/test_tasks.py
Closes #53 and #55
It's possible I've misunderstood the point of `test_tasks.py` and that the _real_ fix for #53 is actually covered by #49, but I was in the area and this was a good learning exercise regardless.
> Fixes for io unit test

- .github/workflows/unit-test.yaml
- ecoscope_workflows/annotations.py
- ecoscope_workflows/connections.py
- tests/test_connections.py
> [`base:patrol`] Revert protocol changes

- ecoscope_workflows/connections.py
- ecoscope_workflows/tasks/io/__init__.py
- ecoscope_workflows/tasks/io/_earthranger.py
- pyproject.toml
- tests/tasks/test_io_earthranger.py
- **Add get_patrol_events**
- **fix unittest**
> Add get_patrol_events task

- .pre-commit-config.yaml
> Fix failing lint.yaml workflow

- ecoscope_workflows/annotations.py
- ecoscope_workflows/decorators.py
- ecoscope_workflows/registry.py
- ecoscope_workflows/tasks/analysis/_aggregation.py
- ecoscope_workflows/tasks/analysis/_time_density.py
- ecoscope_workflows/tasks/io/_earthranger.py
- ecoscope_workflows/tasks/io/_persist.py
- ecoscope_workflows/tasks/preprocessing/_preprocessing.py
- ecoscope_workflows/tasks/results/_dashboard.py
- ecoscope_workflows/tasks/results/_ecomap.py
- ecoscope_workflows/tasks/results/_ecoplot.py
- ecoscope_workflows/tasks/results/_widget_tasks.py
- ecoscope_workflows/tasks/transformation/_exploding.py
- ecoscope_workflows/tasks/transformation/_filtering.py
- ecoscope_workflows/tasks/transformation/_mapping.py
- ecoscope_workflows/templates/script-sequential.jinja2
- ecoscope_workflows/testing.py
- ecoscope_workflows/util.py
- tests/test_decorators.py
- tests/test_type_adapter.py
closes #138 
towards #128 
This is just easier to understand. And closer to our design inspiration of Airflow. "Imitation is the highest form of flattery."
> Rename decorator to `Task` / `@task`

- .github/workflows/unit-test.yaml
- ecoscope_workflows/decorators.py
- ecoscope_workflows/templates/jupytext-macros.jinja
- ecoscope_workflows/templates/script-sequential-macros.jinja
- ecoscope_workflows/testing.py
- examples/dags/mode_map_dag.jupytext.py
- examples/dags/mode_map_dag.script_sequential.py
- examples/dags/patrol_workflow_dag.script_sequential.py
- tests/test_decorators.py
WIP
closes #145
closes #146
closes #148  
towards #128
> Task.partial + Task.validate methods, plus decorator doctests

- ecoscope_workflows/compiler.py
- ecoscope_workflows/jsonschema.py
- ecoscope_workflows/tasks/io/_earthranger.py
- ecoscope_workflows/tasks/preprocessing/_preprocessing.py
- ecoscope_workflows/tasks/results/_ecomap.py
- examples/dags/mode_map_dag.jupytext.py
- examples/params/mode_map_params_fillable.json
- examples/params/patrol_workflow_params_fillable.json
- examples/params/patrol_workflow_params_fillable.yaml
- tests/test_registry.py
- **Generate react-jsonschema-form**
- **default value**
- **enum**
- **fix unittest**
> Generate react-jsonschema-form style

- ecoscope_workflows/tasks/groupby/_groupby.py
- ecoscope_workflows/tasks/io/_persist.py
- ecoscope_workflows/tasks/results/_dashboard.py
- ecoscope_workflows/tasks/results/_ecomap.py
- ecoscope_workflows/tasks/results/_ecoplot.py
- examples/params/mode_map_params_fillable.json
- examples/params/mode_mapvalues_params_fillable.json
- examples/params/patrol_workflow_params_fillable.json
- **Add SkipJsonSchema**
- **update jsonschema**
> Skip null values in react json schema

- ecoscope_workflows/tasks/groupby/__init__.py
- ecoscope_workflows/tasks/groupby/_groupby.py
- ecoscope_workflows/tasks/results/_dashboard.py
- ecoscope_workflows/tasks/transformation/__init__.py
- ecoscope_workflows/tasks/transformation/_indexing.py
- examples/compilation-specs/patrol_workflow.yaml
- examples/dags/patrol_workflow_dag.jupytext.py
- examples/dags/patrol_workflow_dag.script_sequential.py
- examples/params/patrol_workflow_params.yaml
- examples/params/patrol_workflow_params_fillable.json
- examples/params/patrol_workflow_params_fillable.yaml
- tests/tasks/test_groupby.py
- tests/tasks/test_indexing.py
closes #163
also incorporates #170 which closed #169
> Grouped ecomap in patrols workflow (plus tasks  `groupbykey` & `add_temporal_index`)

- ecoscope_workflows/jsonschema.py
- ecoscope_workflows/serde.py
- ecoscope_workflows/tasks/results/_dashboard.py
- pyproject.toml
- tests/tasks/test_dashboard.py
closes #112
closes #151
closes #152
closes #178
> Dashboard results bugfixes

- .readthedocs.yaml
For helping to communicate #179 
closes #136
> Minimal API docs setup with pdoc3 + readthedocs

- .readthedocs.yaml
Oops meant to put #201 into `main`. Here we go.
> Create .readthedocs.yaml (#201)

- pyproject.toml
An attempt to fix some install issues.
> Try dropping tools.setuptools py-modules setting from pyproject.toml

- .github/workflows/ci.yml
- .github/workflows/examples.yml
> Fix pull_request trigger in github workflows

- .github/workflows/ci.yml
- .github/workflows/examples.yml
> Fix github workflows event triggers

- .gitattributes
> Ignore generated files in diffs

- README.md
- examples/mode-map/ecoscope-workflows-mode-map-workflow/pixi.lock
- examples/mode-mapvalues/ecoscope-workflows-mode-mapvalues-workflow/pixi.lock
- examples/patrol-events/ecoscope-workflows-patrol-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
closes #295 
Prioritizing to unblock https://github.com/ecoscope-platform-workflows-releases/patrols/pull/1
> Bump recipe versions to v0.0.2 for release

- examples/mode-map/ecoscope-workflows-mode-map-workflow/Dockerfile
- examples/mode-mapvalues/ecoscope-workflows-mode-mapvalues-workflow/Dockerfile
- examples/patrol-events/ecoscope-workflows-patrol-events-workflow/Dockerfile
- examples/patrols/ecoscope-workflows-patrols-workflow/Dockerfile
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/Dockerfile
- src/ecoscope-workflows-core/ecoscope_workflows_core/compiler.py
- src/ecoscope-workflows-core/ecoscope_workflows_core/templates/Dockerfile.jinja2
> Fix compiler issues for production releases

- examples/mode-map/ecoscope-workflows-mode-map-workflow/pixi.lock
- examples/mode-mapvalues/ecoscope-workflows-mode-mapvalues-workflow/pixi.lock
- examples/patrol-events/ecoscope-workflows-patrol-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
Preparation for releasing `v0.0.3`
> Bump v0.0.3

- examples/patrol-events/ecoscope-workflows-patrol-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
closes #305 (well, almost, will need to tag 0.0.4 after this goes in)
> Bump 0.0.4

- .github/workflows/link_issue.yml
> Enforce PRs Linked with Issues

- examples/patrol-events/ecoscope-workflows-patrol-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/ecoscope_workflows_subject_tracking_workflow/cli.py
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
closes #319
preparing to release 0.0.5 including changes from #312
> Bump 0.0.5

- src/ecoscope-workflows-ext-ecoscope/ecoscope_workflows_ext_ecoscope/tasks/results/_ecomap.py
> fix map widgets

- examples/patrol-events/ecoscope-workflows-patrol-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
> Bump 0.0.6

- examples/events/ecoscope-workflows-events-workflow/ecoscope_workflows_events_workflow/cli.py
- examples/events/test-cases.yaml
- src/ecoscope-workflows-core/ecoscope_workflows_core/tasks/results/_dashboard.py
- src/ecoscope-workflows-core/ecoscope_workflows_core/tasks/results/_widget_tasks.py
- src/ecoscope-workflows-core/ecoscope_workflows_core/tasks/results/_widget_types.py
- src/ecoscope-workflows-core/tests/tasks/test_dashboard.py
- src/ecoscope-workflows-core/tests/tasks/test_widgets.py
> Add is_filtered flag to widgets

- examples/events/ecoscope-workflows-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
> Bump for 0.0.9 release

- examples/events/ecoscope-workflows-events-workflow/pixi.lock
- examples/events/ecoscope-workflows-events-workflow/pixi.toml
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.toml
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.toml
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
- src/ecoscope-workflows-core/ecoscope_workflows_core/compiler.py
- src/ecoscope-workflows-core/tests/test_artifacts.py
> Fix system requirements in pixi toml, and prepare for 0.0.10 release

- examples/events/ecoscope-workflows-events-workflow/pixi.lock
- examples/patrols/ecoscope-workflows-patrols-workflow/pixi.lock
- examples/subject-tracking/ecoscope-workflows-subject-tracking-workflow/pixi.lock
- publish/recipes/release/ecoscope-workflows-core.yaml
- publish/recipes/release/ecoscope-workflows-ext-ecoscope.yaml
> Bump 0.0.12
